# theme: jekyll-theme-cayman
plugins:
  - jekyll-remote-theme
remote_theme: chromatical/jekyll-materialdocs
search: false
theme: jekyll-theme-minimal
include:
  - index.md
  - schedule-phase1.md
  - software.md
